### ISSUE TITLE
MAT does not support Visual Studio 2022 on ARM 64-bit

### ISSUE THREAD

**Issue by BioTurboNick** [microsoft/Multilingual-App-Toolkit#34]
MAT cannot be installed on a Windows on ARM 64-bit system with Visual Studio 2022.

**Comment by MagnusJohansson** [comment]
Same here, here's the log:

It seems that even though it's the "Visual Studio 2022+" extension, it requires an older v15 component?

<details>
<summary>Log file</summary>

```txt
12/10/2024 13:23:52 - Microsoft VSIX Installer
12/10/2024 13:23:52 - -------------------------------------------
12/10/2024 13:23:52 - vsixinstaller.exe version:
12/10/2024 13:23:52 - 17.12.2057-preview3+02e18eb7b9
12/10/2024 13:23:52 - -------------------------------------------
12/10/2024 13:23:52 - Command line parameters:
12/10/2024 13:23:52 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\magnu\Downloads\Microsoft.Multilingual.VSExtension.signed.vsix
12/10/2024 13:23:52 - -------------------------------------------
12/10/2024 13:23:52 - Microsoft VSIX Installer
12/10/2024 13:23:52 - -------------------------------------------
12/10/2024 13:23:54 - Initializing Install...
12/10/2024 13:23:54 - Searching for applicable products...
12/10/2024 13:23:55 - Found installed product - Visual Studio Community 2022
12/10/2024 13:23:55 - Found installed product - Visual Studio Community 2022 Preview
12/10/2024 13:23:55 - Found installed product - Global Location
12/10/2024 13:23:55 - Extension Details...
12/10/2024 13:23:55 - 	Identifier         : MultilingualAppToolkit.Microsoft.bc7f20d6-73ff-4f4d-8084-eb773575c8a5
12/10/2024 13:23:55 - 	Name               : Multilingual App Toolkit v4.1 (VS 2022+)
12/10/2024 13:23:55 - 	Author             : Microsoft
12/10/2024 13:23:55 - 	Version            : 4.2.3
12/10/2024 13:23:55 - 	Description        : Multilingual App Toolkit helps you localize your Windows and Xamarin Apps by providing file management, translation services, translation editor, and build integration.
12/10/2024 13:23:55 - 	Locale             : en-US
12/10/2024 13:23:55 - 	MoreInfoURL        : 
12/10/2024 13:23:55 - 	InstalledByMSI     : False
12/10/2024 13:23:55 - 	SupportedFrameworkVersionRange : [4.5,)
12/10/2024 13:23:57 - 	SignatureState     : ValidSignature
12/10/2024 13:23:57 - 	SignedBy           : Microsoft Corporation
12/10/2024 13:23:57 - 	Certificate Info   : 
12/10/2024 13:23:57 - 		-------------------------------------------------------
12/10/2024 13:23:57 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
12/10/2024 13:23:57 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
12/10/2024 13:23:57 - 		[Serial Number] : 3300000523BAE6749DE1A95064000000000523
12/10/2024 13:23:57 - 		[Not Before]    : 06/04/2023 20:28:17
12/10/2024 13:23:57 - 		[Not After]     : 02/04/2024 20:28:17
12/10/2024 13:23:57 - 		[Thumbprint]    : 9D46CB329871C30878E1C52FA73164474DBD5D29
12/10/2024 13:23:57 - 	Supported Products : 
12/10/2024 13:23:57 - 		Microsoft.VisualStudio.Community
12/10/2024 13:23:57 - 			Version : [17.0,18.0)
12/10/2024 13:23:57 - 			ProductArchitecture : amd64
12/10/2024 13:23:57 - 	References         : 
12/10/2024 13:23:57 - 	Prerequisites      : 
12/10/2024 13:23:57 - 		-------------------------------------------------------
12/10/2024 13:23:57 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/10/2024 13:23:57 - 		Name         : Visual Studio core editor
12/10/2024 13:23:57 - 		Version      : [15.0,)
12/10/2024 13:23:57 - Signature Details...
12/10/2024 13:23:57 - 	Extension is signed with a valid signature.
12/10/2024 13:23:57 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
</details>

**Comment by BioTurboNick** [comment]
That line reads to me as an open-ended interval, as in 15.0+

**Comment by BioTurboNick** [comment]
The "ProductArchitecture" line is probably the important one. `amd64` is not `aarch64`

**Comment by BioTurboNick** [comment]
I wonder if it would be as simple as changing the metadata? Or maybe there's a way to override the checks?

**Comment by BioTurboNick** [comment]
I found a workaround, and it really is just editing the VSIX installer.

1. Change the extension of the installer to .zip
2. Edit "extension.vsixmanifest" to change the ProductArchitecture requirement from "amd64" to "arm64".
3. Edit "_rels\.rels" to remove the Relationship tag pointing to the signature file.
4. Delete the "package" directory (just contains the key for this one).
5. Restore the extension to .vsix

It installs now and all seems to work so far...

**Comment by dpaulino** [comment]
Would love to get proper support for arm64 as well even though a workaround is available
